name: Build Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.actor != 'dependabot[bot]'

    steps:
    - uses: actions/checkout@v3

    # this is a simple way of using date and time to do versioning.
    - name: Modify scripts and get version
      id: version
      run: |
        output=$(date -u '+%Y%m%d%H%M%S')
        echo ::set-output name=date_version::$output
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      if: ${{ github.repository_owner == 'ShinyColorsWiki' && github.ref == 'refs/heads/master' }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/amd64, linux/arm64, linux/arm
        push: ${{ github.repository_owner == 'ShinyColorsWiki' && github.ref == 'refs/heads/master' }}
        tags: |
          ghcr.io/shinycolorswiki/s3-uploader:latest
          ghcr.io/shinycolorswiki/s3-uploader:${{ github.sha }}
          ghcr.io/shinycolorswiki/s3-uploader:${{ steps.version.outputs.date_version }}
        cache-from: type=gha,scope=${{ github.workflow }}
        cache-to: type=gha,mode=max,scope=${{ github.workflow }}